import esbuild from "esbuild";
import process from "node:process";

const banner = `/*
  THIS FILE IS GENERATED BY esbuild.config.mjs.
  See https://github.com/P4suta/aozora-obsidian for source.
*/`;

const isProd = process.argv[2] === "production";

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // The Obsidian runtime + CodeMirror 6 + Lezer are provided by the
  // host application; they MUST stay external or the bundle blows up
  // by ~3 MiB and double-loads CodeMirror inside Obsidian's preview
  // pane. node:* protocol imports are filtered via a plugin (esbuild
  // 0.28+ no longer accepts regex in `external`).
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  plugins: [
    {
      name: "node-protocol-external",
      setup(b) {
        b.onResolve({ filter: /^node:/ }, (args) => ({
          path: args.path,
          external: true,
        }));
      },
    },
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: isProd,
});

if (isProd) {
  await ctx.rebuild();
  await ctx.dispose();
} else {
  await ctx.watch();
}
