// biome-ignore-all lint/style/useNamingConvention: snake_case fields and
// PascalCase property names below mirror the wasm-bindgen-generated
// JS API surface 1:1 — renaming them would break interop with the
// generated `pkg/aozora_wasm.js` glue and with the diagnostics JSON
// shape produced by `aozora::diagnostics_json_view`.

// Typed contract for the `aozora-wasm` npm package (the wasm-bindgen
// JS glue that wraps the `wasm32-unknown-unknown` artifact emitted by
// `wasm-pack build --target web` from
// `aozora/crates/aozora-wasm`).
//
// Right now `aozora-wasm` is NOT yet published to npm — the upstream
// crate's Move 4 status note says wasm-pack is run as part of the
// aozora repo's CI but the resulting `pkg/` is not yet consumable.
// PoC scope: codify the JS surface here so the rest of the plugin
// compiles against the real shape, and load the artifact via
// `WebAssembly.instantiate` against the bytes the bundler will ship
// alongside `main.js` (see `wasm-loader.ts`).
//
// When the real npm package lands, replace this file's body with:
//
//     export { Document, default as init } from "aozora-wasm";
//     export type { InitInput, InitOutput } from "aozora-wasm";
//
// and remove `wasm-loader.ts`'s manual instantiation path. ADR-0001
// records the contract.

/** Mirrors `aozora::Diagnostic` projection in `diagnostics_json_view`. */
export interface AozoraDiagnostic {
  readonly kind:
    | "source_contains_pua"
    | "unclosed_bracket"
    | "unmatched_close"
    | "residual_annotation_marker"
    | "unregistered_sentinel"
    | "registry_out_of_order"
    | "registry_position_mismatch"
    | "unknown";
  readonly span_start: number;
  readonly span_end: number;
  readonly codepoint?: string;
}

/**
 * JS-facing handle to a parsed Aozora document. One-to-one with
 * `aozora::Document` in `crates/aozora-wasm/src/lib.rs`.
 *
 * Construction copies the source string into the WASM heap once; the
 * bumpalo arena is owned WASM-side until the JS handle is GC'd. The
 * methods reuse that arena per call.
 */
export interface AozoraDocument {
  /** Render the document to semantic HTML5. */
  to_html(): string;
  /** Re-emit the canonical Aozora source from the parse tree. */
  serialize(): string;
  /** Diagnostics serialised as a JSON array. */
  diagnostics_json(): string;
  /** Source byte length — handy for progress UI. */
  source_byte_len(): number;
  /** wasm-bindgen-generated cleanup. Idempotent; safe to omit on GC. */
  free(): void;
}

/** wasm-bindgen-generated constructor surface. */
export interface AozoraDocumentCtor {
  new (source: string): AozoraDocument;
}

/**
 * The aggregate shape returned by `wasm-bindgen`'s default export
 * after the WASM has been instantiated. Mirrors the `pkg/aozora_wasm.js`
 * generated by `wasm-pack build --target web`.
 */
export interface AozoraWasmModule {
  readonly Document: AozoraDocumentCtor;
}

/**
 * Plugin-side wrapper around a parsed document. Lifts the WASM
 * `Document` handle into a small TS class that owns its disposal
 * (so the post-processor can `using doc = parser.parse(src);` once
 * we adopt the explicit-resource-management proposal).
 */
export class AozoraDocumentHandle {
  private inner: AozoraDocument;
  private disposed = false;

  constructor(inner: AozoraDocument) {
    this.inner = inner;
  }

  toHtml(): string {
    this.assertLive();
    return this.inner.to_html();
  }

  serialize(): string {
    this.assertLive();
    return this.inner.serialize();
  }

  diagnostics(): readonly AozoraDiagnostic[] {
    this.assertLive();
    const json = this.inner.diagnostics_json();
    // The WASM side guarantees valid JSON — but we still parse
    // defensively because `JSON.parse` is the trust boundary.
    try {
      const parsed: unknown = JSON.parse(json);
      if (!Array.isArray(parsed)) {
        return [];
      }
      return parsed as readonly AozoraDiagnostic[];
    } catch {
      return [];
    }
  }

  sourceByteLen(): number {
    this.assertLive();
    return this.inner.source_byte_len();
  }

  dispose(): void {
    if (!this.disposed) {
      this.inner.free();
      this.disposed = true;
    }
  }

  private assertLive(): void {
    if (this.disposed) {
      throw new Error("AozoraDocumentHandle has been disposed");
    }
  }
}
