import type { MarkdownPostProcessorContext } from "obsidian";
import type { AozoraSettings, GaijiFallback, WritingMode } from "./settings";
import type { AozoraParser } from "./wasm-loader";

/**
 * Markdown post-processor for fenced code blocks tagged ` ```aozora `.
 *
 * Replaces the rendered <pre><code> element with a styled container
 * holding the HTML emitted by `aozora-wasm`'s `Document.to_html()`.
 *
 * Container shape (mirrors `styles.css`):
 *   - class:   `aozora aozora--horizontal | aozora--vertical`
 *   - dataset: `data-aozora-gaiji-mode = image | description | codepoint`
 *
 * The renderer's HTML always carries `data-codepoint` (resolved
 * cells) or `data-description` (unresolved cells) on every
 * `<span class="aozora-gaiji">`; CSS in styles.css uses those
 * attributes plus the dataset on the container to switch between
 * the three gaiji presentations without re-running the parser.
 *
 * Failure modes:
 *   - WASM not yet loaded / load failed → render the raw source
 *     verbatim inside `<pre class="aozora aozora--fallback">` so the
 *     user still sees their content. ADR-0001 says mobile parity is
 *     non-negotiable; a silent failure is worse than a visible-but-
 *     unstyled passage.
 *   - Settings change → the post-processor re-reads `getSettings()`
 *     on every invocation; the host `main.ts` triggers a preview
 *     rerender so toggles take effect immediately.
 */
export interface AozoraProcessorDeps {
  readonly parser: AozoraParser;
  readonly getSettings: () => AozoraSettings;
}

export function createAozoraCodeBlockProcessor(
  deps: AozoraProcessorDeps,
): (source: string, el: HTMLElement, ctx: MarkdownPostProcessorContext) => Promise<void> {
  return async (source, el, _ctx) => {
    const settings = deps.getSettings();
    const container = el.createDiv({ cls: containerClasses(settings.writingMode) });
    container.dataset.aozoraGaijiMode = gaijiDataValue(settings.gaijiFallback);
    try {
      const doc = await deps.parser.parse(source);
      try {
        // SAFETY: `to_html()` is generated by `aozora-render` from a
        // type-checked AST; output is well-formed HTML. The Obsidian
        // preview pane already runs DOMPurify-equivalent sanitisation
        // on rendered child trees, so `innerHTML` is safe here.
        container.innerHTML = doc.toHtml();
        const diagnostics = doc.diagnostics();
        if (diagnostics.length > 0) {
          const note = container.createDiv({ cls: "aozora-diagnostics" });
          note.setText(`aozora: ${diagnostics.length} diagnostic(s)`);
        }
      } finally {
        doc.dispose();
      }
    } catch (err) {
      renderFallback(container, source, err);
    }
  };
}

function containerClasses(mode: WritingMode): string[] {
  return ["aozora", mode === "vertical" ? "aozora--vertical" : "aozora--horizontal"];
}

function gaijiDataValue(mode: GaijiFallback): string {
  return mode;
}

function renderFallback(container: HTMLElement, source: string, err: unknown): void {
  container.addClass("aozora--fallback");
  const message = err instanceof Error ? err.message : String(err);
  const banner = container.createDiv({ cls: "aozora-fallback-banner" });
  banner.setText(`aozora renderer unavailable — showing raw source. ${message}`);
  const pre = container.createEl("pre");
  pre.setText(source);
}
