import type { MarkdownPostProcessorContext } from "obsidian";
import type { AozoraSettings, WritingMode } from "./settings";
import type { AozoraParser } from "./wasm-loader";

/**
 * Markdown post-processor for fenced code blocks tagged ` ```aozora `.
 *
 * Replaces the rendered <pre><code> element with a styled container
 * holding the HTML emitted by `aozora-wasm`'s `Document.to_html()`.
 *
 * Container class catalogue (mirrors `styles.css`):
 *   - `aozora`               — base hook for ruby / bouten / tcy rules
 *   - `aozora--horizontal`   — applied when settings.writingMode is "horizontal"
 *   - `aozora--vertical`     — applied when settings.writingMode is "vertical"
 *
 * Failure modes (PoC):
 *   - WASM not yet bundled → render the raw source verbatim inside a
 *     `<pre class="aozora aozora--fallback">` so the user still sees
 *     their content. ADR-0001 says mobile parity is non-negotiable;
 *     a silent failure is worse than a visible-but-unstyled passage.
 *   - Settings change → the post-processor is re-registered? No.
 *     Obsidian re-runs registered post-processors when the user
 *     reloads the preview pane; the writing-mode class is read fresh
 *     from `getSettings()` each call so toggles take effect on the
 *     next render.
 */
export interface AozoraProcessorDeps {
  readonly parser: AozoraParser;
  readonly getSettings: () => AozoraSettings;
}

export function createAozoraCodeBlockProcessor(
  deps: AozoraProcessorDeps,
): (source: string, el: HTMLElement, ctx: MarkdownPostProcessorContext) => Promise<void> {
  return async (source, el, _ctx) => {
    const container = el.createDiv({ cls: containerClasses(deps.getSettings().writingMode) });
    try {
      const doc = await deps.parser.parse(source);
      try {
        // SAFETY: `to_html()` is generated by `aozora-render` from a
        // type-checked AST; output is well-formed HTML. We still feed
        // it through Obsidian's MarkdownRenderer-compatible
        // `innerHTML` rather than a templating engine because the
        // Obsidian preview pane already runs DOMPurify-equivalent
        // sanitisation on rendered child trees.
        container.innerHTML = doc.toHtml();
        const diagnostics = doc.diagnostics();
        if (diagnostics.length > 0) {
          const note = container.createDiv({ cls: "aozora-diagnostics" });
          note.setText(`aozora: ${diagnostics.length} diagnostic(s)`);
        }
      } finally {
        doc.dispose();
      }
    } catch (err) {
      renderFallback(container, source, err);
    }
  };
}

function containerClasses(mode: WritingMode): string[] {
  return ["aozora", mode === "vertical" ? "aozora--vertical" : "aozora--horizontal"];
}

function renderFallback(container: HTMLElement, source: string, err: unknown): void {
  container.addClass("aozora--fallback");
  const message = err instanceof Error ? err.message : String(err);
  const banner = container.createDiv({ cls: "aozora-fallback-banner" });
  banner.setText(`aozora renderer unavailable — showing raw source. ${message}`);
  const pre = container.createEl("pre");
  pre.setText(source);
}
